name: Bomberman
main: io.github.mdsimmo.bomberman.Bomberman
version: ${version}
load: POSTWORLD

commands:
  bomberman:
    description: Main command for Bomberman
    usage: bomberman <more commands>
    aliases: bm
    permission: bomberman.bm

depend: [WorldEdit]
# SoftDepend Multiverse so Bomberman is loaded after the Multiverse worlds get loaded
softdepend: [Multiverse-Core]

permissions:
  bomberman.*:
    description: Access to all Bomberman commands
    children:
      bomberman.bm: true
      bomberman.dictator: true
      bomberman.operator: true
      bomberman.player: true
  bomberman.player:
    description: Allows join/leave/info
    children:
      bomberman.join: true
      bomberman.leave: true
      bomberman.info: true
      bomberman.list: true
  bomberman.operator:
    description: Allows control of games (start/stop)
    children:
      bomberman.start: true
      bomberman.stop: true
      bomberman.reload: true
  bomberman.dictator:
    description: Allows building/configuring games
    children:
      bomberman.create: true
      bomberman.delete: true
      bomberman.configure: true
  bomberman.bm:
    description: Root bomberman command (/bm)
    default: true
  bomberman.join:
    description: /bm join
    default: true
  bomberman.leave:
    description: /bm join
    default: true
  bomberman.info:
    description: /bm info
    default: true
  bomberman.list:
    description: /bm list
    default: true
  bomberman.start:
    description: /bm start
    default: op
  bomberman.stop:
    description: /bm stop
    default: op
  bomberman.reload:
    description: /bm reload
    default: op
  bomberman.create:
    description: /bm create
    default: op
  bomberman.delete:
    description: /bm delete
    default: op
  bomberman.configure:
    description: /bm configure
    default: op